// Generated by CIRCT 73e28e09a
module Arbiter(	// <stdin>:2:3
  input  req0,	// <stdin>:2:25
         req1,	// <stdin>:2:40
  output grant0,	// <stdin>:2:56
         grant1,	// <stdin>:2:73
  input  clk	// <stdin>:2:89
);

  reg grant1_0 = 1'h0;	// <stdin>:12:14, :13:15
  reg grant0_0 = 1'h0;	// <stdin>:12:14, :19:15
  always @(posedge clk) begin	// <stdin>:21:5
    grant1_0 <= req1 & ~req0;	// <stdin>:10:10, :11:10, :16:7
    grant0_0 <= req0;	// <stdin>:22:7
  end // always @(posedge)
  assign grant0 = grant0_0;	// <stdin>:20:10, :24:5
  assign grant1 = grant1_0;	// <stdin>:14:10, :24:5
endmodule

