// Generated by CIRCT firtool-1.140.0
module my_module(	// <stdin>:2:3
  input  [1:0] sel,	// <stdin>:2:27
  input        a,	// <stdin>:2:41
               b,	// <stdin>:2:53
               c,	// <stdin>:2:65
  output       out_sig,	// <stdin>:2:78
               out2	// <stdin>:2:96
);

  assign out_sig = sel == 2'h1 ? a : sel == 2'h2 ? b : c;	// <stdin>:6:15, :7:10, :8:10, :9:14, :10:10, :11:10, :12:5
  assign out2 = sel == 2'h0 ? a : b;	// <stdin>:3:14, :4:10, :5:10, :12:5
endmodule

