// Generated by CIRCT firtool-1.140.0
module child_module(	// <stdin>:2:3
  input  in1,	// <stdin>:2:30
  output out1	// <stdin>:2:45
);

  assign out1 = ~in1;	// <stdin>:4:10, :5:5
endmodule

module my_module(	// <stdin>:7:3
  input  clk,	// <stdin>:7:27
         a,	// <stdin>:7:41
         b,	// <stdin>:7:53
  output out_sig	// <stdin>:7:66
);

  wire _my_inst_out1;	// <stdin>:8:21
  reg  out_sig_0;	// <stdin>:17:16
  always_ff @(posedge clk)	// <stdin>:19:5
    out_sig_0 <= a | ~b & _my_inst_out1;	// <stdin>:8:21, :15:10, :16:10, :20:7
  child_module my_inst (	// <stdin>:8:21
    .in1  (a),
    .out1 (_my_inst_out1)
  );	// <stdin>:8:21
  assign out_sig = out_sig_0;	// <stdin>:18:10, :22:5
endmodule

