// Generated by CIRCT 9ee7ebc99
module sync_2ff(	// <stdin>:2:3
  input  clk_dst,	// <stdin>:2:34
         d_in,	// <stdin>:2:52
  output d_out	// <stdin>:2:68
);

  reg stage1 = 1'h0;	// <stdin>:9:14, :10:15
  reg d_out_0 = 1'h0;	// <stdin>:9:14, :16:14
  always @(posedge clk_dst) begin	// <stdin>:18:5
    stage1 <= d_in;	// <stdin>:13:7
    d_out_0 <= stage1;	// <stdin>:11:10, :19:7
  end // always @(posedge)
  assign d_out = d_out_0;	// <stdin>:17:10, :21:5
endmodule

module test_cdc_ok(	// <stdin>:23:3
  input  clk_slow,	// <stdin>:23:29
         clk_fast,	// <stdin>:23:48
         data_in,	// <stdin>:23:67
  output result	// <stdin>:23:86
);

  wire _u_sync_d_out;	// <stdin>:36:21
  reg  data_reg = 1'h0;	// <stdin>:30:14, :31:17
  always @(posedge clk_slow)	// <stdin>:33:5
    data_reg <= data_in;	// <stdin>:34:7
  reg  result_0 = 1'h0;	// <stdin>:30:14, :38:15
  always @(posedge clk_fast)	// <stdin>:40:5
    result_0 <= _u_sync_d_out;	// <stdin>:36:21, :41:7
  sync_2ff u_sync (	// <stdin>:36:21
    .clk_dst (clk_fast),
    .d_in    (data_reg),	// <stdin>:32:10
    .d_out   (_u_sync_d_out)
  );	// <stdin>:36:21
  assign result = result_0;	// <stdin>:39:10, :43:5
endmodule

