// Generated by CIRCT 9ab3a65c9
module hier_child(	// <stdin>:2:3
  input  in1,	// <stdin>:2:36
  output out1	// <stdin>:2:51
);

  assign out1 = ~in1;	// <stdin>:4:10, :5:5
endmodule

module hier_top(	// <stdin>:7:3
  input  top_in,	// <stdin>:7:26
  output top_out	// <stdin>:7:44
);

  wire _u_child_out1;	// <stdin>:8:21
  assert property (~top_in | ~_u_child_out1);	// <stdin>:8:21, :12:10, :14:10, :15:10, :16:5
  hier_child u_child (	// <stdin>:8:21
    .in1  (top_in),
    .out1 (_u_child_out1)
  );	// <stdin>:8:21
  assign top_out = _u_child_out1;	// <stdin>:8:21, :17:5
endmodule

