// Generated by CIRCT 9ab3a65c9
module hier_top(	// <stdin>:2:3
  input  top_in,	// <stdin>:2:26
  output top_out	// <stdin>:2:44
);

  wire _u_child_out1;	// <stdin>:3:21
  assert property (~top_in | ~_u_child_out1);	// <stdin>:3:21, :7:10, :9:10, :10:10, :11:5
  hier_child u_child (	// <stdin>:3:21
    .in1  (top_in),
    .out1 (_u_child_out1)
  );	// <stdin>:3:21
  assign top_out = _u_child_out1;	// <stdin>:3:21, :12:5
endmodule

module hier_child(	// <stdin>:14:3
  input  in1,	// <stdin>:14:36
  output out1	// <stdin>:14:51
);

  assign out1 = ~in1;	// <stdin>:16:10, :17:5
endmodule

