// Generated by CIRCT 73e28e09a
module pass_through(	// <stdin>:2:3
  input  clk,	// <stdin>:2:30
         a,	// <stdin>:2:44
  output z	// <stdin>:2:57
);

  assign z = a;	// <stdin>:11:5
endmodule

