// Generated by CIRCT 9ab3a65c9
module child_module(	// <stdin>:2:3
  input  in1,	// <stdin>:2:38
  output out1	// <stdin>:2:53
);

  assign out1 = ~in1;	// <stdin>:4:10, :5:5
endmodule

module my_module(	// <stdin>:7:3
  input  clk,	// <stdin>:7:27
         a,	// <stdin>:7:41
         b,	// <stdin>:7:53
  output out_sig	// <stdin>:7:66
);

  wire _my_inst_out1;	// <stdin>:12:21
  reg  out_sig_0 = 1'h0;	// <stdin>:18:14, :22:16
  always @(posedge clk)	// <stdin>:24:5
    out_sig_0 <= a | ~b & _my_inst_out1;	// <stdin>:12:21, :19:10, :20:10, :25:7
  child_module my_inst (	// <stdin>:12:21
    .in1  (a),
    .out1 (_my_inst_out1)
  );	// <stdin>:12:21
  assign out_sig = out_sig_0;	// <stdin>:23:10, :27:5
endmodule

