// Generated by CIRCT 9ab3a65c9
module arbiter_starve(	// <stdin>:2:3
  input  req0,	// <stdin>:2:32
         req1,	// <stdin>:2:47
  output grant0,	// <stdin>:2:63
         grant1,	// <stdin>:2:80
  input  clk	// <stdin>:2:96
);

  reg grant0_0 = 1'h0;	// <stdin>:12:14, :19:15
  reg grant1_0 = 1'h0;	// <stdin>:12:14, :34:15
  always @(posedge clk) begin	// <stdin>:36:5
    grant0_0 <= req0;	// <stdin>:22:7
    grant1_0 <= ~req0 & req1;	// <stdin>:32:11, :37:7
  end // always @(posedge)
  assign grant0 = grant0_0;	// <stdin>:20:10, :41:5
  assign grant1 = grant1_0;	// <stdin>:35:11, :41:5
endmodule

