// Generated by CIRCT 9ab3a65c9
module test_pass_mutation(	// <stdin>:2:3
  input        clk,	// <stdin>:2:36
               rst,	// <stdin>:2:50
  input  [3:0] a,	// <stdin>:2:64
               b,	// <stdin>:2:76
  output [3:0] c	// <stdin>:2:89
);

  reg [3:0] c_0 = 4'h0;	// <stdin>:9:14, :13:10
  always @(posedge clk)	// <stdin>:15:5
    c_0 <= rst ? 4'h0 : a + b;	// <stdin>:9:14, :10:10, :11:10, :16:7
  assert property (@(posedge clk) ~rst & a == 4'h2 & b == 4'h3 |-> ##1 c_0 == 4'h5);	// <stdin>:14:10, :19:10, :20:14, :21:10, :22:10, :23:14, :24:10, :25:10, :26:14, :27:11, :28:11, :29:11, :31:5
  assign c = c_0;	// <stdin>:14:10, :32:5
endmodule

