// Generated by CIRCT 9ab3a65c9
module bounded_counter(	// <stdin>:2:3
  input        inc,	// <stdin>:2:33
               clk,	// <stdin>:2:47
  output [3:0] val	// <stdin>:2:62
);

  reg [3:0] count = 4'h0;	// <stdin>:12:14, :13:14
  always @(posedge clk)	// <stdin>:15:5
    count <= inc ? count + 4'h1 : count;	// <stdin>:9:14, :10:10, :11:10, :14:10, :16:7
  assign val = count;	// <stdin>:14:10, :23:5
endmodule

