// Generated by CIRCT 9ab3a65c9
module test_fail_konami(	// <stdin>:2:3
  input  clk,	// <stdin>:2:34
         rst,	// <stdin>:2:48
         up,	// <stdin>:2:62
         down,	// <stdin>:2:75
         left,	// <stdin>:2:90
         right,	// <stdin>:2:105
  output unlock	// <stdin>:2:122
);

  reg [2:0] state = 3'h0;	// <stdin>:11:14, :69:14
  reg       unlock_0 = 1'h0;	// <stdin>:76:14, :128:15
  always @(posedge clk) begin	// <stdin>:130:5
    automatic logic _GEN = state == 3'h0 & up;	// <stdin>:11:14, :13:10, :16:10, :70:11
    automatic logic _GEN_0 = state == 3'h5 & right;	// <stdin>:31:15, :32:11, :35:11, :70:11
    automatic logic _GEN_1 = state == 3'h4 & left;	// <stdin>:38:15, :39:11, :42:11, :70:11
    automatic logic _GEN_2 = state == 3'h3 & down;	// <stdin>:45:14, :46:11, :49:11, :70:11
    automatic logic _GEN_3 = state == 3'h2 & down;	// <stdin>:52:14, :53:11, :56:11, :70:11
    automatic logic _GEN_4 = state == 3'h1 & up;	// <stdin>:17:14, :60:11, :63:11, :70:11
    state <=
      rst
        ? 3'h0
        : _GEN
            ? 3'h1
            : _GEN_4
                ? 3'h2
                : _GEN_3
                    ? 3'h3
                    : _GEN_2
                        ? 3'h4
                        : _GEN_1
                            ? 3'h5
                            : _GEN_0 ? 3'h6 : up | down | left | right ? 3'h0 : state;	// <stdin>:11:14, :16:10, :17:14, :22:10, :25:11, :28:11, :30:11, :31:15, :35:11, :36:15, :37:11, :38:15, :42:11, :44:11, :45:14, :49:11, :51:11, :52:14, :56:11, :58:11, :63:11, :65:11, :66:11, :67:11, :70:11, :72:7
    unlock_0 <= ~rst & ~_GEN & ~_GEN_4 & ~_GEN_3 & ~_GEN_2 & ~_GEN_1 & _GEN_0;	// <stdin>:16:10, :35:11, :42:11, :49:11, :56:11, :63:11, :106:11, :112:11, :118:11, :124:11, :125:11, :126:11, :131:7
  end // always @(posedge)
  assert property (~unlock_0);	// <stdin>:129:11, :134:11, :135:5
  assign unlock = unlock_0;	// <stdin>:129:11, :136:5
endmodule

