// Generated by CIRCT 73e28e09a
module sticky_high(	// <stdin>:2:3
  input  clk,	// <stdin>:2:29
         rst,	// <stdin>:2:43
  output s	// <stdin>:2:58
);

  reg s_sig = 1'h0;	// <stdin>:13:14, :14:14
  reg _GEN = 1'h0;	// <stdin>:13:14, :21:10
  always @(posedge clk) begin	// <stdin>:23:5
    s_sig <= rst | s_sig;	// <stdin>:12:10, :15:10, :17:7
    _GEN <= _GEN | rst;	// <stdin>:19:10, :22:10, :24:7
  end // always @(posedge)
  assert property (~_GEN | rst | s_sig);	// <stdin>:15:10, :22:10, :27:10, :28:10, :29:11, :30:5
  assign s = s_sig;	// <stdin>:15:10, :31:5
endmodule

