// Generated by CIRCT 179c31994
module test_cdc_ok(	// <stdin>:2:3
  input  clk_slow,	// <stdin>:2:29
         clk_fast,	// <stdin>:2:48
         data_in,	// <stdin>:2:67
  output result	// <stdin>:2:86
);

  wire _u_sync_d_out;	// <stdin>:15:21
  reg  data_reg = 1'h0;	// <stdin>:9:14, :10:17
  always @(posedge clk_slow)	// <stdin>:12:5
    data_reg <= data_in;	// <stdin>:13:7
  reg  result_0 = 1'h0;	// <stdin>:9:14, :17:15
  always @(posedge clk_fast)	// <stdin>:19:5
    result_0 <= _u_sync_d_out;	// <stdin>:15:21, :20:7
  sync_2ff u_sync (	// <stdin>:15:21
    .clk_dst (clk_fast),
    .d_in    (data_reg),	// <stdin>:11:10
    .d_out   (_u_sync_d_out)
  );	// <stdin>:15:21
  assign result = result_0;	// <stdin>:18:10, :22:5
endmodule

module sync_2ff(	// <stdin>:24:3
  input  clk_dst,	// <stdin>:24:34
         d_in,	// <stdin>:24:52
  output d_out	// <stdin>:24:68
);

  reg stage1 = 1'h0;	// <stdin>:31:14, :32:15
  reg d_out_0 = 1'h0;	// <stdin>:31:14, :38:14
  always @(posedge clk_dst) begin	// <stdin>:40:5
    stage1 <= d_in;	// <stdin>:35:7
    d_out_0 <= stage1;	// <stdin>:33:10, :41:7
  end // always @(posedge)
  assign d_out = d_out_0;	// <stdin>:39:10, :43:5
endmodule

