// Generated by CIRCT 9ab3a65c9
module delay_mismatch(	// <stdin>:2:3
  input  req,	// <stdin>:2:32
         clk,	// <stdin>:2:46
  output ack	// <stdin>:2:61
);

  reg ack_0 = 1'h0;	// <stdin>:7:14, :8:12
  always @(posedge clk)	// <stdin>:10:5
    ack_0 <= req;	// <stdin>:11:7
  assert property (~req | ack_0);	// <stdin>:9:10, :14:10, :15:10, :16:5
  assign ack = ack_0;	// <stdin>:9:10, :17:5
endmodule

