// Generated by CIRCT 9ab3a65c9
module test_fail_counter(	// <stdin>:2:3
  input        clk,	// <stdin>:2:35
               rst,	// <stdin>:2:49
               req,	// <stdin>:2:63
  output [3:0] cnt_out	// <stdin>:2:78
);

  reg [3:0] cnt = 4'h0;	// <stdin>:9:14, :17:12
  always @(posedge clk)	// <stdin>:19:5
    cnt <= rst ? 4'h0 : req ? cnt + 4'h1 : cnt;	// <stdin>:9:14, :12:14, :13:10, :14:10, :15:10, :18:10, :20:7
  assert property (cnt != 4'h3);	// <stdin>:18:10, :22:14, :23:10, :24:5
  assign cnt_out = cnt;	// <stdin>:18:10, :25:5
endmodule

