// Generated by CIRCT 9ab3a65c9
module invert_wrong_contract(	// <stdin>:2:3
  input  clk,	// <stdin>:2:39
         a,	// <stdin>:2:53
  output z	// <stdin>:2:66
);

  assign z = ~a;	// <stdin>:4:10, :9:5
endmodule

