// Generated by CIRCT 73e28e09a
module my_module(	// <stdin>:2:3
  input  clk,	// <stdin>:2:27
         req,	// <stdin>:2:41
  output ack	// <stdin>:2:56
);

  reg ack_0 = 1'h0;	// <stdin>:11:14, :12:12
  reg _GEN = 1'h0;	// <stdin>:11:14, :18:10
  reg _GEN_0 = 1'h0;	// <stdin>:11:14, :28:10
  always @(posedge clk) begin	// <stdin>:30:5
    ack_0 <= req;	// <stdin>:15:7
    _GEN <= req;	// <stdin>:21:7
    _GEN_0 <= req;	// <stdin>:31:7
  end // always @(posedge)
  assert property ((~_GEN | ack_0) & req == _GEN_0);	// <stdin>:13:10, :19:10, :24:10, :25:10, :29:10, :33:11, :35:11, :36:5
  assign ack = ack_0;	// <stdin>:13:10, :37:5
endmodule

