// Generated by CIRCT 9ab3a65c9
module burst_next(	// <stdin>:2:3
  input  req,	// <stdin>:2:28
         clk,	// <stdin>:2:42
  output valid_out	// <stdin>:2:57
);

  reg       active = 1'h0;	// <stdin>:11:14, :23:15
  reg [1:0] cnt = 2'h0;	// <stdin>:17:14, :41:12
  reg       valid_out_0 = 1'h0;	// <stdin>:11:14, :60:18
  always @(posedge clk) begin	// <stdin>:62:5
    automatic logic _GEN = cnt == 2'h0;	// <stdin>:17:14, :18:10, :42:11
    active <= ~active ? req | active : ~_GEN & active;	// <stdin>:12:10, :16:10, :18:10, :20:10, :21:10, :24:10, :26:7
    cnt <= ~active ? (req ? 2'h2 : cnt) : _GEN ? cnt : cnt - 2'h1;	// <stdin>:12:10, :18:10, :24:10, :32:15, :33:11, :37:11, :38:11, :39:11, :42:11, :44:7
    valid_out_0 <= ~active ? req : ~_GEN;	// <stdin>:12:10, :18:10, :20:10, :24:10, :58:11, :63:7
  end // always @(posedge)
  assert property (~req | valid_out_0);	// <stdin>:61:11, :66:11, :67:11, :77:5
  assert property (@(posedge clk) req |-> ##1 valid_out_0);	// <stdin>:61:11, :68:11, :69:11, :78:5
  assert property (@(posedge clk) req |-> ##2 valid_out_0);	// <stdin>:61:11, :71:11, :72:11, :79:5
  assert property (@(posedge clk) req |-> ##3 valid_out_0);	// <stdin>:61:11, :74:11, :75:11, :80:5
  assign valid_out = valid_out_0;	// <stdin>:61:11, :81:5
endmodule

