// Generated by CIRCT 9ab3a65c9
module Arbiter(	// <stdin>:2:3
  input  req0,	// <stdin>:2:25
         req1,	// <stdin>:2:40
  output grant0,	// <stdin>:2:56
         grant1,	// <stdin>:2:73
  input  clk	// <stdin>:2:89
);

  assign grant0 = req0;	// <stdin>:21:5
  assign grant1 = req1;	// <stdin>:21:5
endmodule

