// Generated by CIRCT 9ab3a65c9
module timer(	// <stdin>:2:3
  input        clk,	// <stdin>:2:23
               reset,	// <stdin>:2:37
               en,	// <stdin>:2:53
  input  [7:0] limit,	// <stdin>:2:66
  output       done	// <stdin>:2:83
);

  reg  [7:0] count = 8'h0;	// <stdin>:15:14, :25:14
  wire       _GEN = count == limit;	// <stdin>:8:10, :26:11
  always @(posedge clk)	// <stdin>:27:5
    count <= reset ? 8'h0 : en ? (~_GEN ? count + 8'h1 : 8'h0) : count;	// <stdin>:8:10, :11:14, :12:10, :14:10, :15:14, :16:10, :22:10, :23:10, :26:11, :28:7
  assign done = _GEN;	// <stdin>:8:10, :30:5
endmodule

