// Generated by CIRCT 9ab3a65c9
module test_fail_off_by_one(	// <stdin>:2:3
  input  clk,	// <stdin>:2:38
         rst,	// <stdin>:2:52
         start,	// <stdin>:2:66
  output done	// <stdin>:2:83
);

  reg done_0 = 1'h0;	// <stdin>:13:14, :22:13
  reg delay1 = 1'h0;	// <stdin>:13:14, :37:15
  reg delay2 = 1'h0;	// <stdin>:13:14, :52:15
  always @(posedge clk) begin	// <stdin>:54:5
    done_0 <= ~rst & (start & delay1 ? delay1 : delay2);	// <stdin>:18:10, :19:10, :20:10, :25:7, :38:11, :53:11
    delay1 <= ~rst & start;	// <stdin>:20:10, :35:11, :40:7
    delay2 <= ~rst & delay1;	// <stdin>:20:10, :38:11, :50:11, :55:7
  end // always @(posedge)
  assert property (@(posedge clk) start |-> ##3 done_0);	// <stdin>:23:10, :61:11, :62:11, :64:5
  assign done = done_0;	// <stdin>:23:10, :65:5
endmodule

