// Generated by CIRCT 73e28e09a
module handshake(	// <stdin>:2:3
  input  clk,	// <stdin>:2:27
         req,	// <stdin>:2:41
  output ack	// <stdin>:2:56
);

  reg ack_0 = 1'h0;	// <stdin>:11:14, :12:12
  reg _GEN = 1'h0;	// <stdin>:11:14, :18:10
  reg _GEN_0 = 1'h0;	// <stdin>:11:14, :27:10
  always @(posedge clk) begin	// <stdin>:29:5
    ack_0 <= req;	// <stdin>:15:7
    _GEN <= req;	// <stdin>:21:7
    _GEN_0 <= req;	// <stdin>:30:7
  end // always @(posedge)
  assume property (~_GEN | req);	// <stdin>:19:10, :24:10, :25:10, :35:5
  assert property (~_GEN_0 | ack_0);	// <stdin>:13:10, :28:10, :33:11, :34:11, :36:5
  assign ack = ack_0;	// <stdin>:13:10, :37:5
endmodule

