// Generated by CIRCT 9ab3a65c9
module my_module(	// <stdin>:2:3
  input  clk,	// <stdin>:2:27
         a,	// <stdin>:2:41
         b,	// <stdin>:2:53
  output out_sig	// <stdin>:2:66
);

  reg out_sig_0 = 1'h0;	// <stdin>:13:14, :17:16
  always @(posedge clk)	// <stdin>:19:5
    out_sig_0 <= a;	// <stdin>:20:7
  assign out_sig = out_sig_0;	// <stdin>:18:10, :22:5
endmodule

