// Generated by CIRCT 73e28e09a
module next_delay_demo(	// <stdin>:2:3
  input  clk,	// <stdin>:2:33
         req,	// <stdin>:2:47
  output ack	// <stdin>:2:62
);

  reg d2 = 1'h0;	// <stdin>:13:14, :14:11
  reg d3 = 1'h0;	// <stdin>:13:14, :20:11
  reg ack_0 = 1'h0;	// <stdin>:13:14, :26:12
  reg d1 = 1'h0;	// <stdin>:13:14, :32:11
  always @(posedge clk) begin	// <stdin>:34:5
    d2 <= d1;	// <stdin>:17:7, :33:10
    d3 <= d2;	// <stdin>:15:10, :23:7
    ack_0 <= d3;	// <stdin>:21:10, :29:7
    d1 <= req;	// <stdin>:35:7
  end // always @(posedge)
  assert property (@(posedge clk) req |-> ##4 ack_0);	// <stdin>:27:10, :37:10, :38:10, :43:5
  assert property (@(posedge clk) req |-> ##[2:5] ack_0);	// <stdin>:27:10, :40:11, :41:11, :44:5
  assign ack = ack_0;	// <stdin>:27:10, :45:5
endmodule

