// Generated by CIRCT 9ab3a65c9
module alu(	// <stdin>:2:3
  input  [1:0] opcode,	// <stdin>:2:21
  input  [7:0] a,	// <stdin>:2:38
               b,	// <stdin>:2:50
  output [7:0] res	// <stdin>:2:63
);

  wire [3:0][7:0] _GEN = {{a ^ b}, {a & b}, {a - b}, {a + b}};	// <stdin>:3:10, :5:10, :6:10, :7:10, :9:10, :10:10, :11:10, :13:10, :14:10, :15:10
  assign res = _GEN[opcode];	// <stdin>:5:10, :7:10, :9:10, :11:10, :13:10, :15:10, :16:5
endmodule

