// Generated by CIRCT 73e28e09a
// FORMAL TEST: pass_through_CheckContract_0 {}
module pass_through_CheckContract_0(	// build.mlir:3:8
  input symbolic_value_0
);

  wire _GEN = ~symbolic_value_0;	// build.mlir:5:10
  assume property (_GEN);	// build.mlir:5:10, :6:5
  assert property (_GEN);	// build.mlir:5:10, :9:5
endmodule

