// Generated by CIRCT 73e28e09a
module pass_through(	// build.mlir:1:1
  input  clk,	// build.mlir:1:28
         a,	// build.mlir:1:41
  output z	// build.mlir:1:53
);

  assert property (~a);	// build.mlir:5:10, :6:5
  assign z = 1'h0;	// build.mlir:11:3
endmodule

