// Generated by CIRCT firtool-1.140.0
module my_module(	// <stdin>:2:3
  input  clk,	// <stdin>:2:27
         req,	// <stdin>:2:41
  output ack	// <stdin>:2:56
);

  reg ack_0;	// <stdin>:3:12
  always_ff @(posedge clk)	// <stdin>:5:5
    ack_0 <= req;	// <stdin>:6:7
  assert property (req |-> ack_0);	// <stdin>:4:10, :8:10, :9:5
  assert property (req |-> (s_eventually ack_0));	// <stdin>:4:10, :10:10, :11:10, :12:5
  assign ack = ack_0;	// <stdin>:4:10, :15:5
endmodule

