// Generated by CIRCT firtool-1.140.0
module timer(	// <stdin>:2:3
  input        clk,	// <stdin>:2:23
               reset,	// <stdin>:2:37
               en,	// <stdin>:2:53
  input  [7:0] limit,	// <stdin>:2:66
  output       done	// <stdin>:2:83
);

  reg  [7:0] count;	// <stdin>:20:14
  wire       _GEN = count == limit;	// <stdin>:4:10, :21:10
  always_ff @(posedge clk)	// <stdin>:22:5
    count <= reset ? 8'h0 : en ? (~_GEN ? count + 8'h1 : 8'h0) : count;	// <stdin>:4:10, :7:14, :8:10, :10:10, :11:14, :12:10, :18:10, :19:10, :21:10, :23:7
  assign done = _GEN;	// <stdin>:4:10, :25:5
endmodule

