// Generated by CIRCT 9ab3a65c9
module test_live(	// <stdin>:2:3
  input req,	// <stdin>:2:27
        ack,	// <stdin>:2:41
        clk	// <stdin>:2:55
);

  assert property (@(posedge clk) req |-> (s_eventually ack));	// <stdin>:3:10, :4:10, :6:5
endmodule

