// Generated by CIRCT firtool-1.140.0
module processor_core
  #(parameter DATA_WIDTH = 16) (	// <stdin>:2:3
  input        clk,	// <stdin>:2:54
               reset,	// <stdin>:2:68
               en,	// <stdin>:2:84
  input  [1:0] opcode,	// <stdin>:2:97
  input        operandA,	// <stdin>:2:114
               operandB,	// <stdin>:2:133
  output       result	// <stdin>:2:153
);

  wire [3:0] _GEN =
    {{operandA ^ operandB},
     {operandA & operandB},
     {operandA - operandB},
     {operandA + operandB}};	// <stdin>:3:10, :5:10, :6:10, :7:10, :9:10, :10:10, :11:10, :13:10, :14:10, :15:10
  reg        reg_out;	// <stdin>:28:16
  always_ff @(posedge clk)	// <stdin>:30:5
    reg_out <= ~reset & (en ? _GEN[opcode] : reg_out);	// <stdin>:5:10, :7:10, :9:10, :11:10, :13:10, :15:10, :26:11, :27:11, :29:11, :31:7
  assert property (reset |-> ~_GEN[opcode]);	// <stdin>:5:10, :7:10, :9:10, :11:10, :13:10, :15:10, :18:11, :33:11, :34:5
  assign result = reg_out;	// <stdin>:29:11, :37:5
endmodule

module system_top(	// <stdin>:39:3
  input         sys_clk,	// <stdin>:39:28
                sys_rst,	// <stdin>:39:46
                sys_en,	// <stdin>:39:64
  input  [31:0] opA_0,	// <stdin>:39:81
                opB_0,	// <stdin>:39:98
                opA_1,	// <stdin>:39:115
                opB_1,	// <stdin>:39:132
  output [31:0] out_0,	// <stdin>:39:150
                out_1	// <stdin>:39:167
);

  assign out_0 = 32'h0;	// <stdin>:40:15, :42:5
  assign out_1 = 32'h0;	// <stdin>:40:15, :42:5
endmodule

