// Generated by CIRCT 9ab3a65c9
module Test(	// <stdin>:2:3
  input  clk,	// <stdin>:2:22
         req,	// <stdin>:2:36
  output ack	// <stdin>:2:51
);

  reg ack_0 = 1'h0;	// <stdin>:7:14, :8:12
  always @(posedge clk)	// <stdin>:10:5
    ack_0 <= req;	// <stdin>:11:7
  cover property (req & ack_0);	// <stdin>:9:10, :15:10, :18:5
  assert property (~(~req & ack_0));	// <stdin>:9:10, :20:10, :21:10, :25:10, :26:5
  assign ack = ack_0;	// <stdin>:9:10, :27:5
endmodule

