// Generated by CIRCT 9ab3a65c9
module test_live_pass(	// <stdin>:2:3
  input  req,	// <stdin>:2:32
  output ack,	// <stdin>:2:47
  input  clk	// <stdin>:2:60
);

  assign ack = req;	// <stdin>:5:5
endmodule

